spring:
  application:
    name: saga-orchestrator

server:
  port: 8083

order-service:
  url: http://localhost:8082

payment-service:
  url: http://localhost:8081


resilience4j:
  retry:
    instances:
      paymentServiceRetry:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - java.lang.RuntimeException