spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: Manick@123

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

